### PR TITLE
> 95% unit test coverage and refactoring.

### PR DESCRIPTION
**Pull request by shivros**
I didn't realize until now that GitHub didn't have private messaging - I planned on sending you a preliminary message before opening this. 

Let me preface this by saying that I 100% realize this merge request is ridiculously expansive, and I understand if you're uncomfortable merging it in as-is. Furthermore, some of the README badge links (e.g. build, test coverage, maintainability) have to be changed in order to properly merge this back into the main project.

I was trying to use the original PSAW as a pip dependency in my  project and hit up against a few pagination issues. So I've tried to contribute as much testing and stability as I could to the project you created.

I'd love to work with you on getting some form of this testing merged in.

### CODE REVIEW

**Comment by dmarx** [comment]
So yeah, this is pretty amazing. Let me play with it a little and I'll try to pull tonight

**Comment by shivros** [comment]
Sounds good. Let me know if you hit any issues!

Edit: Easiest way to get everything working right away is running `make create-venv` and `source venv/bin/activate`.

**Comment by dmarx** [comment]
I really appreciate the work you put in here, but the fact remains: you're boiling the ocean. Not only is this a ton to review, but there are several substantive changes that are not called out (e.g. changing the default subdomain from 'api' to 'apiv2', which isn't correct). Additionally, you make a lot of unnecessary stylistic changes that I don't like (e.g. replacing single quotes with double quotes everywhere) which are completely unrelated to the main contribution. If you don't like my coding style, we can discuss code standards for the project separately.

Let's break this up into a couple of separate pulls. Your biggest contribution here is the testing suite: I especially appreciate that work and want to incorporate it ASAP. Let's get testing up and running on the current code base before making a million changes to it that I need to review individually with a fine toothed comb. That way, if I'm satisfied with the tests you wrote and we commit them upstream of other changes you're thinking of suggesting, the tests will serve their purpose and help me vet the code for you're other changes. And if I don't like certain downstream changes, I don't need to reject all of your other contributions like I am now.

But as it stands, I'm forced to go through your code commit-by-commit. I can't even diff the head of my master branch with yours because you changed the formatting on everything so every single modification is obfuscated.

Let's do this one piece at a time. Separate unrelated commits into distinct pull requests so I can better understand what's going on.

**Comment by shivros** [comment]
Happy to work on breaking it down. I'll hit the testing first, but I'm going to be gone for the next few weeks, so this'll have to be on the backburner until late August.

**Comment by dmarx** [comment]
I'd like to start incorporating some of your work, esp. testing and CI. You put a lot of work into this, so I understand if you want to have your name on the commits rather than me cannibalizing your work and committing it under my name. Do you expect you'll have a chance to get back to this any time soon? Or do you mind if I pick up where you left off, even if that means you won't have your name attached to the commits I merge into master?

This is the first project I've owned where I actually got any kind of community participation. I know some people are really into github's "social" features, and I want to give you the opportunity to bump your stats if that's something you care about. You def earned it. If you don't care alt- that stuff, I'll at least add a "CONTRIBUTORS" file and include you to ensure you're at least credited for your significant contributions to the project.

Thanks again!

**Pull request closed without merging**
